import { FastifyInstance } from "fastify";

/**
 * Local Scalar integration. The OpenAPI document is generated by
 * @fastify/swagger from the registered route schemas; this file only mounts
 * the generated JSON and Scalar's browser reference.
 */
export function registerDocs(app: FastifyInstance): void {
  app.get("/api/v1/openapi.json", async (_request, reply) => {
    reply.type("application/json").send(app.swagger());
  });

  app.get("/api/v1/docs", async (_request, reply) => {
    reply.type("text/html; charset=utf-8").send(`<!doctype html>
<html>
  <head>
    <title>CKB Wallet Behaviour Registry API</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <script id="api-reference" data-url="/api/v1/openapi.json"></script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  </body>
</html>`);
  });
}
